[package]
name = "rutag"
version = "0.1.0"
authors = ["wojciechkepka <wojtek.kepka@protonmail.com>"]
edition = "2018"

[[bin]]
name = "rutag"
path = "src/main.rs"

[dependencies]
libc = "0.2"
thiserror = "1"
clap = "3.0.0-beta.2"
serde_json = "1"
chrono = "0.4"
