[package]
name = "wutag"
description = "Tag files and manage them with color"
version = "0.7.1"
authors = [
  "wojciechkepka <wojtek.kepka@protonmail.com>",
  "Lucas Burns <lmb@lmburns.com>",
]
edition = "2018"
repository = "https://github.com/lmburns/wutag"
categories = ["command-line-utilities", "filesystem", "tagging"]
keywords = ["cli", "shell", "utility", "tag", "files"]
readme = "README.md"

[lib]
name = "wutag_core"
path = "wutag_core/lib.rs"

[features]
default = ["encrypt-gpgme", "ui"]

_encrypt-gpg = []

encrypt-gpgme = ["gpgme", "secstr", "zeroize"]
ui = [
  "tui",
  "rustyline",
  "rustyline-derive",
  "unicode-segmentation",
  "unicode-width",
  "cassowary",
  "better-panic",
]

[dependencies]
# Used for lscolors
ansi_term = "0.12.1"
anyhow = "1.0.43"
atty = "0.2.14"
base64 = "0.13.0"
chrono = { version = "0.4.19", features = ["serde"] }
clap = "3.0.0-beta.5"
clap_generate = "3.0.0-beta.5"
colored = { git = "https://github.com/wojciechkepka/colored", branch = "master", features = ["serde"] }
crossbeam-channel = "0.5.1"
crossbeam-utils = "0.8.5"
dirs = "3.0.2"
env_logger = "0.9.0"
globset = "0.4.8"
ignore = "0.4.18"
lexiclean = "0.0.1"
libc = "0.2.100"
log = "0.4.14"
lscolors = "0.7.1"
num_cpus = "1.13.0"
once_cell = "1.8.0"
rand = "0.8.4"
rayon = "1.5.1"
regex = "1.5.4"
serde = { version = "1.0.129", features = ["derive"] }
serde_cbor = "0.11.2"
serde_json = "1.0.66"
serde_yaml = "0.8.19"
shellexpand = "2.1.0"
thiserror = "1.0.26"
toml = "0.5.8"
itertools = "0.10.1"
strip-ansi-escapes = "0.1.1"

# TODO: use or remove
termion = "1.5.5"
rusqlite = "0.26.1"

# TODO: add formatted option
cli-table = "0.4.6"

# ADD to TUI?
crossterm = { version = "0.20.0", default-features = false }

# Default feature - tui
tui = { version = "0.16.0", features = ["crossterm"], optional = true }
rustyline = { version = "9.0.0", optional = true }
rustyline-derive = { version = "0.5.0", optional = true }
unicode-segmentation = { version = "1.8.0", optional = true }
unicode-width = { version = "0.1.9", optional = true }
cassowary = { version = "0.3.0", optional = true }
better-panic = { version = "0.2.0", optional = true }

# Default feature - encryption
gpgme = { version = "0.10.0", optional = true }
secstr = { version = "0.4.0", optional = true }
zeroize = { version = "1.4.3", optional = true }

[dev-dependencies]
predicates = "2.0.1"
tempfile = "3.2.0"
serial_test = "0.5.0"
assert_cmd = "2.0.0"
# wait-timeout = "0.2.0"
# tempdir = "0.3.7"
# gag = "0.1.10"

[profile.release]
lto = true
