[package]
name = "wutag"
description = "Tag files and manage them with color"
version = "0.4.5"
authors = ["wojciechkepka <wojtek.kepka@protonmail.com>", "Lucas Burns <lmb@lmburns.com>"]
edition = "2018"
repository = "https://github.com/lmburns/wutag"
categories = ["command-line-utilities", "filesystem", "tagging"]
keywords = ["cli", "shell", "utility", "tag", "files"]
readme = "README.md"

[lib]
name = "wutag_core"
path = "wutag_core/lib.rs"

[dependencies]
anyhow = "1"
libc = "0.2"
thiserror = "1"
clap = "3.0.0-beta.2"
clap_generate = "3.0.0-beta.2"
serde_yaml = "0.8"
serde_cbor = "0.11"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
walkdir = "2"
colored = { git = "https://github.com/wojciechkepka/colored", branch = "master", features = ["serde"] }
globwalk = "0.8"
rand = "0.8"
base64 = "0.13.0"
dirs = "3"
shellexpand = "2.1.0"
globset = "0.4.8"
lscolors = "0.7.1"
ansi_term = "0.12.1"
atty = "0.2.14"
tabwriter = "1.2.1"
ignore = "0.4.18"
regex = "1.5.4"
lazy_static = "1.4.0"

[dev-dependencies]
tempdir = "0.3"
