name: release

on:
  push:
    branches:
      - "!*"
    tags:
      - "**"


jobs:
  codestyle:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
        with:
          components: rustfmt
          rust-version: stable
      - uses: actions/checkout@v1
      - run: cargo fmt --all -- --check

  lint:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
        with:
          components: clippy
      - uses: actions/checkout@v1
      - run: cargo clippy --all-targets -- -D clippy::all

  compile:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
      - uses: actions/checkout@master
      - run: cargo check --all

  test:
    needs: [codestyle, lint, compile]
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      - name: Checkout
        uses: actions/checkout@v1
      - name: Test
        run: cargo test

  build_and_upload_artifacts:
    name: Upload Artifacts
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
      - uses: actions/checkout@master
      - run: cargo build --release
      - name: Get version
        run: |
          echo "WUTAG_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "version is: ${{ env.WUTAG_VERSION }}"
      - name: Upload binary
        uses: svenstaro/upload-release-action@v2
        with:
          repo_name: wojciechkepka/wutag
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/relese/wutag
          asset_name: wutag-${{ env.WUTAG_VERSION }}
          tag: ${{ env.WUTAG_VERSION }}
          overwrite: true



